name: Build krane
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: |
          curl -s https://gw.alipayobjects.com/os/enclose-prod/1fd23e6b-d48f-4ed0-94dd-f0f539960253/rubyc-v0.4.0-linux-x64.gz | gunzip > rubyc &&
          chmod +x rubyc &&
          sudo mv rubyc /usr/local/bin
      - run: sudo apt install squashfs-tools build-essential
      - run: ./pack.sh
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: krane
          path: krane/krane